# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0004_user_random_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_user_id',
            field=models.CharField(editable=False, max_length=120, unique=True, verbose_name='Random User Id'),
        ),
    ]
