# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 01:29
from __future__ import unicode_literals

import HarperUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0005_auto_20170210_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='random_user_id',
            field=models.CharField(default=HarperUser.models.random_id, editable=False, max_length=120, unique=True, verbose_name='Random User Id'),
        ),
    ]
