# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0007_user_avatar_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='e_contact_full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='e_contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('medical_administrator', 'Medical Administrator')], default=None, max_length=120, null=True, verbose_name='What is your role?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, choices=[('CPA', 'CPA'), ('Esq', 'Esq.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('JD', 'JD'), ('Jr.', 'Jr.'), ('M.D.', 'M.D.'), ('Ph. D.', 'Ph. D.'), ('Sr.', 'Sr.')], default='', max_length=120, verbose_name='Name Suffix'),
        ),
    ]
