# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0008_auto_20170630_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=1, max_length=60, verbose_name='Middle Name'),
            preserve_default=False,
        ),
    ]
