# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0009_user_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numner',
            new_name='phone_number',
        ),
    ]
