# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0011_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_signup_profile',
            field=models.BooleanField(default=False, verbose_name='User Signup Profile'),
        ),
    ]
