# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0012_user_user_signup_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_signup_set_up',
            field=models.BooleanField(default=False, verbose_name='User Signup Set Up'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('medical_administrator', 'Medical Administrator')], default='patient', max_length=120, null=True, verbose_name='What is your role?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=60, verbose_name='Phone Number'),
        ),
    ]
