# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0014_auto_20170716_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='are_you_a_health_care_prof',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=120, null=True, verbose_name='Are you a healthcare professional?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=120, verbose_name='Would you like to receive email notifications?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_did_you_hear_about_us',
            field=models.CharField(choices=[('online', 'Online'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('friend', 'Friend'), ('news', 'News')], default='online', max_length=120, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_many_doctor_visits',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8+', '8+')], default='1', max_length=120, verbose_name='How many visits do you have a month?'),
        ),
    ]
