# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0015_auto_20170716_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='how_many_doctor_visits',
        ),
        migrations.AddField(
            model_name='user',
            name='healthcare_role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('medical_administrator', 'Medical Administrator')], default='patient', max_length=120, null=True, verbose_name='What is your role?'),
        ),
        migrations.AddField(
            model_name='user',
            name='how_many_doctor_visits_month',
            field=models.IntegerField(default='1', max_length=120, verbose_name='How many visits do you have a month?'),
        ),
        migrations.AddField(
            model_name='user',
            name='how_many_doctor_visits_week',
            field=models.IntegerField(default='1', max_length=120, verbose_name='How many visits do you have a week?'),
        ),
        migrations.AddField(
            model_name='user',
            name='how_many_doctor_visits_year',
            field=models.IntegerField(default='1', max_length=120, verbose_name='How many visits do you have a year?'),
        ),
        migrations.AddField(
            model_name='user',
            name='what_health_care_type',
            field=models.CharField(default=1, max_length=120, verbose_name='What medical field are you in?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='what_medical_type_are_you',
            field=models.CharField(default=1, max_length=120, verbose_name='What kind of medical professional are you?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='are_you_a_health_care_prof',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=120, null=True, verbose_name='Are you a healthcare professional?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='yes', max_length=120, verbose_name='Would you like to receive email notifications?'),
        ),
    ]
