# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0016_auto_20170716_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='healthcare_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='yes', max_length=120, verbose_name='Would you like to receive email notifications?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_many_doctor_visits_month',
            field=models.IntegerField(default='1', verbose_name='How many medical related visits do you have a month?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_many_doctor_visits_week',
            field=models.IntegerField(default='1', verbose_name='How many medical related visits do you have a week?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_many_doctor_visits_year',
            field=models.IntegerField(default='1', verbose_name='How many medical related visits do you have a year?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='what_medical_type_are_you',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('pa', 'Physicians Assistant '), ('dentist', 'Dentist'), ('other', 'other')], max_length=120, verbose_name='What kind of medical professional are you?'),
        ),
    ]
