# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 23:21
from __future__ import unicode_literals

import HarperUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0018_user_patient_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='yes', max_length=120, verbose_name='Would you like to receive email notifications from harper?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='random_user_id',
            field=models.CharField(default=HarperUser.models.random_id, max_length=120, unique=True, verbose_name='Random User Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='what_medical_type_are_you',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('pa', 'Physicians Assistant '), ('dentist', 'Dentist'), ('other', 'Other')], default='nurse', max_length=120, verbose_name='What kind of medical professional are you?'),
        ),
    ]
