# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 19:29
from __future__ import unicode_literals

import HarperUser.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0019_auto_20170716_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(max_length=120, verbose_name='LEGACY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=120, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=HarperUser.models.random_id, help_text='Required. 255 characters or fewer. Letters, numbers and             @/./+/-/_ characters', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Username'),
        ),
    ]
