# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0021_auto_20170718_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=120, verbose_name='Gender'),
        ),
    ]
