# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0023_auto_20170722_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='are_you_a_health_care_prof',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=120, null=True, verbose_name='Are you a healthcare professional?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='yes', max_length=120, verbose_name='Would you like to receive email notifications?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient_email_notifications',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='no', max_length=120, verbose_name='Would you like to notify your patients using harper that you have signed up?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='what_medical_type_are_you',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('doctor', 'Doctor'), ('Physicians Assistant', 'Physicians Assistant'), ('Dentist', 'Dentist'), ('Other', 'Other')], default='nurse', max_length=120, verbose_name='What kind of medical professional are you?'),
        ),
    ]
