# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0024_auto_20170723_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='harperbot_updates',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='yes', max_length=120, verbose_name='Would you like Harperbot to provide your information and updates?'),
        ),
    ]
