# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0025_user_harperbot_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=120, verbose_name='Would you like to receive email notifications?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='harperbot_updates',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=120, verbose_name='Would you like Harperbot to provide your information and updates?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_did_you_hear_about_us',
            field=models.CharField(choices=[('online', 'Online'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('friend', 'Friend'), ('news', 'News')], default='Online', max_length=120, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient_email_notifications',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=120, verbose_name='Would you like to notify your patients using harper that you have signed up?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='what_medical_type_are_you',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('doctor', 'Doctor'), ('Physicians Assistant', 'Physicians Assistant'), ('Dentist', 'Dentist'), ('Other', 'Other')], default='Doctor', max_length=120, verbose_name='What kind of medical professional are you?'),
        ),
    ]
