# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0027_auto_20170723_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='what_health_care_type',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='What medical field are you in?'),
        ),
    ]
