# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0028_auto_20170723_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='are_you_a_health_care_prof',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=120, null=True, verbose_name='Are you a healthcare professional?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='what_medical_type_are_you',
            field=models.CharField(blank=True, choices=[('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Physicians Assistant', 'Physicians Assistant'), ('Dentist', 'Dentist'), ('Other', 'Other')], default='', max_length=120, verbose_name='What kind of medical professional are you?'),
        ),
    ]
