# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0031_auto_20170725_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='harper_bot_pop_up',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=120, verbose_name='Would you like Harperbot to automatically pop up when it have an update?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient_email_notifications',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=120, verbose_name='Would you like your patients using harper to be able to find you account?'),
        ),
    ]
