# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0032_auto_20170728_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='are_you_over_the_age_of_18',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', help_text='By saying yes to this box, you agree electronically that you are 18 or older.', max_length=120, verbose_name='Are you over the age of 18?'),
        ),
    ]
