# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarperUser', '0033_user_are_you_over_the_age_of_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_new_password',
            field=models.BooleanField(default=False, verbose_name='Needs New Password'),
        ),
    ]
